import { AlertTriangle, Activity, ArrowRight, Clock3, LockKeyhole, ScanSearch, Shield, ShieldCheck, Sparkles, TrendingUp, UsersRound, Zap } from "lucide-react";
import { StatCard } from "@/components/StatCard";
import { SafetyScoreRing } from "@/components/SafetyScoreRing";
import { AlertCard } from "@/components/AlertCard";
import { ChildCard } from "@/components/ChildCard";
import { useStore } from "@/lib/store";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";

const categoryColors = ["hsl(222,58%,24%)", "hsl(172,55%,38%)", "hsl(37,92%,49%)", "hsl(1,72%,55%)", "hsl(270,58%,58%)", "hsl(205,79%,51%)"];
const minutes = (total: number) => `${Math.floor(total / 60)}h ${total % 60}m`;

export default function Dashboard() {
  const { alerts, children, platforms, weeklyActivity } = useStore();
  const openAlerts = alerts.filter((a) => a.status === "open");
  const unread = openAlerts.filter((a) => !a.isRead);
  const overallScore = children.length ? Math.round(children.reduce((sum, child) => sum + child.safetyScore, 0) / children.length) : 100;
  const threatsBlocked = platforms.reduce((sum, p) => sum + p.threatsBlocked, 0);
  const monitoredEvents = platforms.reduce((sum, p) => sum + p.monitoredEvents, 0);
  const avgScreenTime = children.length ? Math.round(children.reduce((sum, c) => sum + c.screenTimeMinutes, 0) / children.length) : 0;
  const categoryMap = alerts.reduce<Record<string, number>>((map, alert) => { map[alert.threatType] = (map[alert.threatType] || 0) + 1; return map; }, {});
  const categories = Object.entries(categoryMap).map(([name, count]) => ({ name, count })).filter((item) => item.name !== "No Significant Risk");
  const detectionRate = monitoredEvents ? Math.round((threatsBlocked / monitoredEvents) * 1000) / 10 : 0;
  const recent = [...alerts].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 3);
  const protectedCount = children.filter((c) => c.status === "safe").length;

  return <div className="space-y-7">
    <section className="security-grid relative overflow-hidden rounded-[28px] border bg-card p-6 shadow-card sm:p-8">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_0%,hsl(var(--secondary)/0.14),transparent_30%)]" />
      <div className="relative grid gap-8 xl:grid-cols-[1.25fr_0.75fr]">
        <div>
          <div className="flex flex-wrap items-center gap-2"><span className="eyebrow">Family security command center</span><span className="rounded-full border border-success/20 bg-success/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[0.12em] text-success">All systems nominal</span></div>
          <h2 className="mt-3 max-w-2xl font-display text-3xl font-bold tracking-tight text-balance sm:text-4xl">See risk early. <span className="text-secondary">Respond with confidence.</span></h2>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">CyberShield turns digital safety signals into an explainable workflow for monitoring, triage and response.</p>
          <div className="mt-6 flex flex-wrap gap-2.5"><Link to="/analyzer" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5"><ScanSearch className="h-4 w-4" />Analyze content</Link><Link to="/simulator" className="inline-flex items-center gap-2 rounded-xl border bg-background/80 px-4 py-2.5 text-sm font-semibold transition hover:bg-muted"><Zap className="h-4 w-4 text-secondary" />Run event lab</Link></div>
          <div className="mt-7 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl border bg-background/70 p-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Children</p><p className="mt-1 font-display text-xl font-bold">{children.length}</p></div><div className="rounded-2xl border bg-background/70 p-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Protected</p><p className="mt-1 font-display text-xl font-bold">{protectedCount}</p></div><div className="rounded-2xl border bg-background/70 p-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Open incidents</p><p className="mt-1 font-display text-xl font-bold">{openAlerts.length}</p></div><div className="rounded-2xl border bg-background/70 p-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Detection rate</p><p className="mt-1 font-display text-xl font-bold">{detectionRate}%</p></div></div>
        </div>
        <div className="rounded-[26px] border bg-slate-950 p-6 text-white shadow-elevated"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.15em] text-white/45">Current posture</p><p className="mt-1 text-sm font-semibold text-white/85">Family safety score</p></div><Shield className="h-5 w-5 text-emerald-300" /></div><div className="mt-7 flex items-center gap-6"><SafetyScoreRing score={overallScore} size={132} strokeWidth={11} className="[&_.text-foreground]:text-white [&_.text-muted-foreground]:text-white/45" /><div className="space-y-3"><div><p className="text-[10px] uppercase tracking-[0.12em] text-white/35">Status</p><p className="mt-1 text-lg font-semibold">{overallScore >= 85 ? "Strong" : overallScore >= 70 ? "Watch" : "At risk"}</p></div><div><p className="text-[10px] uppercase tracking-[0.12em] text-white/35">Signals</p><p className="mt-1 text-sm text-white/70">{unread.length} unread · {openAlerts.length} open</p></div></div></div><div className="mt-6 flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-[10px] text-white/55"><ShieldCheck className="h-3.5 w-3.5 text-emerald-300" /> Explainable local detection is active</div></div>
      </div>
    </section>

    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Overall safety" value={`${overallScore}%`} subtitle="Across all children" icon={Shield} variant="primary" /><StatCard title="Open incidents" value={openAlerts.length} subtitle={`${unread.length} unread · attention needed`} icon={AlertTriangle} variant="danger" /><StatCard title="Threats blocked" value={threatsBlocked} subtitle={`${detectionRate}% of modeled events`} icon={ShieldCheck} variant="success" /><StatCard title="Avg. screen time" value={minutes(avgScreenTime)} subtitle="Per child today" icon={Clock3} /></section>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-3">
      <div className="panel xl:col-span-2 p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Telemetry</p><h3 className="mt-1 font-display text-lg font-bold">Safety activity</h3><p className="mt-1 text-xs text-muted-foreground">Detected vs. blocked signals across the current demo week.</p></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary/10 text-secondary"><Activity className="h-5 w-5" /></div></div><div className="mt-6 h-[230px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={weeklyActivity}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} stroke="hsl(var(--muted-foreground))" fontSize={11} /><YAxis axisLine={false} tickLine={false} stroke="hsl(var(--muted-foreground))" fontSize={11} allowDecimals={false} /><Tooltip contentStyle={{ backgroundColor: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: "14px", fontSize: "11px" }} /><Line type="monotone" dataKey="threats" name="Detected" stroke="hsl(var(--destructive))" strokeWidth={3} dot={{ r: 3 }} /><Line type="monotone" dataKey="blocked" name="Blocked" stroke="hsl(var(--secondary))" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></div>
      <div className="panel p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Risk distribution</p><h3 className="mt-1 font-display text-lg font-bold">Threat mix</h3><p className="mt-1 text-xs text-muted-foreground">Incidents by category.</p></div><TrendingUp className="h-5 w-5 text-secondary" /></div>{categories.length ? <><div className="mt-4 h-[190px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} cx="50%" cy="50%" innerRadius={55} outerRadius={78} paddingAngle={3} dataKey="count">{categories.map((entry, index) => <Cell key={entry.name} fill={categoryColors[index % categoryColors.length]} />)}</Pie><Tooltip contentStyle={{ backgroundColor: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: "14px", fontSize: "11px" }} /></PieChart></ResponsiveContainer></div><div className="space-y-2">{categories.slice(0, 6).map((cat, index) => <div key={cat.name} className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-muted-foreground"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: categoryColors[index % categoryColors.length] }} /><span className="truncate">{cat.name}</span></span><span className="font-bold text-foreground">{cat.count}</span></div>)}</div></> : <div className="flex h-[245px] flex-col items-center justify-center text-center"><ShieldCheck className="h-10 w-10 text-success" /><p className="mt-3 font-semibold">No incidents yet</p><p className="mt-1 text-xs text-muted-foreground">Run the event lab to populate the system.</p></div>}</div>
    </section>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-3"><div className="panel xl:col-span-2 overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4 sm:px-6"><div><p className="eyebrow">Family</p><h3 className="mt-1 font-display text-lg font-bold">Children at a glance</h3></div><Link to="/children" className="text-xs font-bold text-primary hover:underline">Manage family</Link></div><div className="grid gap-4 p-5 sm:p-6 lg:grid-cols-2">{children.slice(0, 4).map((child) => <ChildCard key={child.id} child={child} />)}</div></div><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><p className="eyebrow">Response queue</p><h3 className="mt-1 font-display text-lg font-bold">Latest incidents</h3></div><Link to="/alerts" className="text-xs font-bold text-primary">View all</Link></div><div className="space-y-3 p-4">{recent.map((alert) => <AlertCard key={alert.id} alert={alert} />)}</div></div></section>

    <section className="rounded-2xl border bg-gradient-to-r from-primary/[0.96] via-primary/[0.98] to-secondary/[0.92] p-5 text-white shadow-elevated sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white/10"><Sparkles className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/50">Recommended next step</p><h3 className="mt-1 font-display text-lg font-bold">Demonstrate the full incident pipeline</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-white/65">Trigger a simulated event, inspect the incident details, resolve it, and watch the posture change across the dashboard.</p></div></div><Link to="/simulator" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-primary transition hover:-translate-y-0.5">Open Event Lab <ArrowRight className="h-4 w-4" /></Link></div></section>

    <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><div className="panel p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><UsersRound className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Family profiles</p><p className="font-display text-xl font-bold">{children.length}</p></div></div></div><div className="panel p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-secondary/10 p-2.5 text-secondary"><LockKeyhole className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Active services</p><p className="font-display text-xl font-bold">{platforms.filter((p) => p.status === "active").length}/{platforms.length}</p></div></div></div><div className="panel p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-success/10 p-2.5 text-success"><Zap className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Events modeled</p><p className="font-display text-xl font-bold">{monitoredEvents}</p></div></div></div></div>
  </div>;
}
