import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { Activity, ArrowRight, Eye, EyeOff, Loader2, LockKeyhole, Shield, ShieldCheck, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/contexts/AuthContext";

export default function Login() {
  const [email, setEmail] = useState("demo@cybershield.app");
  const [password, setPassword] = useState("CyberShield123!");
  const [show, setShow] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const message = (location.state as { registered?: boolean } | null)?.registered ? "Account created. You can sign in now." : "";
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(""); setLoading(true); try { await login(email.trim(), password); navigate("/", { replace: true }); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in."); } finally { setLoading(false); } };

  return <div className="min-h-screen bg-background p-4 sm:p-6 lg:p-8">
    <div className="mx-auto grid min-h-[calc(100vh-2rem)] max-w-6xl overflow-hidden rounded-[30px] border bg-card shadow-elevated lg:grid-cols-[1.05fr_0.95fr]">
      <section className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-14"><div className="absolute inset-0 opacity-30 security-grid" /><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-secondary/20 blur-3xl" /><div className="relative"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white p-1"><Shield className="h-7 w-7 text-primary" /></div><div><p className="font-display text-xl font-bold">CyberShield</p><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-white/35">Safety intelligence</p></div></div><div className="mt-24 max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.15em] text-white/65"><Sparkles className="h-3.5 w-3.5 text-secondary" /> Local-first security console</span><h1 className="mt-5 font-display text-5xl font-bold leading-[1.05] tracking-tight xl:text-6xl">See risk early.<br /><span className="text-secondary">Respond with confidence.</span></h1><p className="mt-6 max-w-md text-sm leading-6 text-white/50">An explainable child-safety command center for detection, incident triage and responsible digital protection.</p></div></div><div className="relative grid grid-cols-3 gap-2 text-[10px]"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><ShieldCheck className="h-4 w-4 text-emerald-300" /><p className="mt-2 font-semibold">Explainable</p><p className="mt-0.5 text-white/35">Rule-backed</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><LockKeyhole className="h-4 w-4 text-sky-300" /><p className="mt-2 font-semibold">Private</p><p className="mt-0.5 text-white/35">Local demo</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><Activity className="h-4 w-4 text-amber-300" /><p className="mt-2 font-semibold">Actionable</p><p className="mt-0.5 text-white/35">Incident flow</p></div></div></section>

      <section className="flex items-center p-6 sm:p-10 xl:p-14"><div className="mx-auto w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary text-white"><Shield className="h-6 w-6" /></div><div><p className="font-display text-xl font-bold">CyberShield</p><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-muted-foreground">Safety intelligence</p></div></div></div><div><p className="eyebrow">Secure workspace</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Welcome back</h2><p className="mt-2 text-sm text-muted-foreground">Sign in to continue to your family security console.</p></div><form onSubmit={submit} className="mt-8 space-y-5">{message && <div className="rounded-xl border border-success/15 bg-success/10 p-3 text-xs font-medium text-success">{message}</div>}{error && <div className="rounded-xl border border-destructive/15 bg-destructive/10 p-3 text-xs font-medium text-destructive">{error}</div>}<div className="space-y-2"><Label htmlFor="email">Email address</Label><Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-11 rounded-xl" required /></div><div className="space-y-2"><div className="flex items-center justify-between"><Label htmlFor="password">Password</Label><span className="text-[10px] font-semibold text-muted-foreground">Demo access</span></div><div className="relative"><Input id="password" type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} className="h-11 rounded-xl pr-10" required /><button type="button" onClick={() => setShow((v) => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><Button type="submit" className="h-11 w-full rounded-xl text-sm font-semibold" disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <><span>Enter CyberShield</span><ArrowRight className="h-4 w-4" /></>}</Button></form><div className="mt-6 rounded-2xl border bg-muted/30 p-4"><div className="flex items-start gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><LockKeyhole className="h-4 w-4" /></div><div><p className="text-xs font-bold">Demo credentials</p><p className="mt-1 text-[11px] text-muted-foreground">demo@cybershield.app · CyberShield123!</p></div></div></div><p className="mt-6 text-center text-sm text-muted-foreground">New here? <Link to="/register" className="font-semibold text-primary hover:underline">Create an account</Link></p></div></section>
    </div>
  </div>;
}
