import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Shield, Eye, EyeOff, Loader2, Check, X } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/contexts/AuthContext";

export default function Register() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const navigate = useNavigate(); const { register } = useAuth();
  const strength = password.length >= 12 && /[A-Z]/.test(password) && /[0-9]/.test(password) && /[^A-Za-z0-9]/.test(password);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(""); if (!name.trim() || !email.trim() || password.length < 8 || password !== confirm) { setError("Use a valid name/email, an 8+ character password, and matching passwords."); return; } setLoading(true); try { await register(name.trim(), email.trim(), password); navigate("/", { replace: true }); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create account."); } finally { setLoading(false); } };
  const item = (ok: boolean, label: string) => <div className="flex items-center gap-1.5 text-xs">{ok ? <Check className="h-3.5 w-3.5 text-success" /> : <X className="h-3.5 w-3.5 text-muted-foreground" />}<span className={ok ? "text-success" : "text-muted-foreground"}>{label}</span></div>;
  return <div className="flex min-h-screen items-center justify-center bg-background px-4 py-8"><Card className="w-full max-w-md shadow-elevated"><CardHeader className="items-center text-center"><div className="mb-2 flex h-14 w-14 items-center justify-center rounded-2xl gradient-primary"><Shield className="h-7 w-7 text-white" /></div><CardTitle className="text-2xl font-display">Create your workspace</CardTitle><CardDescription>Start a local CyberShield family safety dashboard.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{error && <div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<div className="space-y-2"><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Alex Morgan" required /></div><div className="space-y-2"><Label>Email</Label><Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required /></div><div className="space-y-2"><Label>Password</Label><div className="relative"><Input type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create a strong password" required /><button type="button" onClick={() => setShow((v) => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><div className="space-y-1">{item(password.length >= 8, "At least 8 characters")}{item(/[A-Z]/.test(password) && /[0-9]/.test(password), "Uppercase letter and number")}{item(/[^A-Za-z0-9]/.test(password), "Special character")}{item(strength, "Strong password")}</div><div className="space-y-2"><Label>Confirm password</Label><Input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></div><Button className="w-full" disabled={loading} type="submit">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Create workspace"}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already have an account? <Link to="/login" className="font-semibold text-primary hover:underline">Sign in</Link></p></CardContent></Card></div>;
}
