import { Bell, Shield, Eye, Clock3, RotateCcw, Database, UserRound, Download, Trash2, Cloud, RefreshCw, ServerCog, ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";
import { useStore, type SafetySettings } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

function ToggleSetting({ label, description, value, onChange }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void }) {
  return <div className="flex items-center justify-between gap-5 py-3"><div><p className="text-sm font-medium text-foreground">{label}</p><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{description}</p></div><button type="button" aria-pressed={value} onClick={() => onChange(!value)} className={cn("relative h-6 w-11 flex-shrink-0 rounded-full transition-colors", value ? "bg-secondary" : "bg-muted")}><span className={cn("absolute top-0.5 left-0.5 h-5 w-5 rounded-full bg-card shadow transition-transform", value && "translate-x-5")} /></button></div>;
}

export default function SettingsPage() {
  const { settings, updateSetting, resetDemo, exportSnapshot, clearLocalData, clearCloudWorkspace, syncNow, backendMode, isSyncing, syncError, isHydrated } = useStore(); const { user } = useAuth();
  const group = (title: string, icon: React.ReactNode, keys: Array<{ key: keyof SafetySettings; label: string; description: string }>) => <section className="rounded-2xl border bg-card p-5 shadow-card sm:p-6"><div className="mb-3 flex items-center gap-2"><div className="text-secondary">{icon}</div><h2 className="font-display font-semibold">{title}</h2></div>{keys.map((item) => <ToggleSetting key={item.key} label={item.label} description={item.description} value={settings[item.key]} onChange={(value) => { updateSetting(item.key, value); toast.success(`${item.label} ${value ? "enabled" : "disabled"}`); }} />)}</section>;
  return <div className="max-w-3xl space-y-6"><div><h1 className="font-display text-3xl font-bold tracking-tight">Settings</h1><p className="mt-1 text-muted-foreground">Configure safety behavior, privacy controls and workspace persistence.</p></div>
    <section className="rounded-2xl border bg-card p-5 shadow-card sm:p-6"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-5 w-5" /></div><div><p className="font-semibold">{user?.name || "Demo Parent"}</p><p className="text-sm text-muted-foreground">{user?.email || "demo@cybershield.app"}</p></div></div></section>
    {group("Notifications", <Bell className="h-5 w-5" />, [{ key: "pushNotifications", label: "Push notifications", description: "Receive instant alerts for critical safety events." }, { key: "emailDigest", label: "Email digest", description: "Prepare a daily summary of activity and alerts." }, { key: "smsAlerts", label: "SMS alerts", description: "Demo preference for critical-level notifications." }])}
    {group("Privacy", <Shield className="h-5 w-5" />, [{ key: "onDeviceProcessing", label: "On-device processing", description: "Prefer local analysis to reduce data transmission." }, { key: "anonymousReporting", label: "Anonymous reporting", description: "Remove direct identifiers from demo threat reports." }, { key: "autoDataPurge", label: "Auto data purge", description: "Represent a policy to delete threat metadata after 30 days." }])}
    {group("Detection", <Eye className="h-5 w-5" />, [{ key: "strictMode", label: "Strict mode", description: "Increase sensitivity at the cost of more false positives." }, { key: "profanityFilter", label: "Profanity filter", description: "Include mild language in the local demo rule set." }, { key: "imageAnalysis", label: "Image analysis", description: "Reserve a control for future authorized image analysis." }])}
    {group("Screen time", <Clock3 className="h-5 w-5" />, [{ key: "screenTimeLimits", label: "Screen time limits", description: "Keep daily usage-limit controls enabled." }, { key: "bedtimeMode", label: "Bedtime mode", description: "Represent device quiet-hour policies." }, { key: "appSpecificLimits", label: "App-specific limits", description: "Enable per-app time-limit planning." }])}
    <section className="rounded-2xl border bg-card p-5 shadow-card sm:p-6"><div className="mb-3 flex items-center gap-2"><Database className="h-5 w-5 text-secondary" /><h2 className="font-display font-semibold">Privacy & data controls</h2></div><p className="text-sm leading-6 text-muted-foreground">CyberShield uses a local-first workspace. With Supabase configured, the same state is encrypted in transit and stored in a user-scoped database row protected by Row Level Security.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-muted/30 p-3"><Cloud className="h-4 w-4 text-secondary" /><p className="mt-2 text-xs font-bold">{backendMode === "cloud" ? "Cloud sync" : "Local mode"}</p><p className="mt-1 text-[10px] text-muted-foreground">{backendMode === "cloud" ? (isSyncing ? "Syncing workspace…" : syncError ? "Sync error — check connection" : "RLS-protected workspace") : "No external data transfer"}</p></div><div className="rounded-xl border bg-muted/30 p-3"><ShieldCheck className="h-4 w-4 text-success" /><p className="mt-2 text-xs font-bold">Session</p><p className="mt-1 text-[10px] text-muted-foreground">{isHydrated ? "Workspace loaded" : "Loading workspace…"}</p></div><div className="rounded-xl border bg-muted/30 p-3"><ServerCog className="h-4 w-4 text-primary" /><p className="mt-2 text-xs font-bold">Schema</p><p className="mt-1 text-[10px] text-muted-foreground">Workspace schema v2</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => { exportSnapshot(); toast.success("Workspace export started"); }}><Download className="mr-2 h-4 w-4" />Export workspace</Button><Button variant="outline" onClick={() => { void syncNow().then(() => toast.success("Workspace synced")).catch((e) => toast.error(e instanceof Error ? e.message : "Sync failed")); }} disabled={backendMode !== "cloud" || isSyncing}><RefreshCw className="mr-2 h-4 w-4" />Sync now</Button><Button variant="outline" onClick={() => { resetDemo(); toast.success("Demo data reset"); }}><RotateCcw className="mr-2 h-4 w-4" />Reset demo</Button><Button variant="outline" className="border-destructive/30 text-destructive hover:bg-destructive/5" onClick={() => { clearLocalData(); toast.success("Local cache cleared"); }}><Trash2 className="mr-2 h-4 w-4" />Clear local cache</Button>{backendMode === "cloud" && <Button variant="outline" className="border-destructive/30 text-destructive hover:bg-destructive/5" onClick={() => { void clearCloudWorkspace().then(() => toast.success("Cloud workspace deleted")).catch((e) => toast.error(e instanceof Error ? e.message : "Unable to delete cloud workspace")); }}><Trash2 className="mr-2 h-4 w-4" />Delete cloud workspace</Button>}</div></section>
  </div>;
}
